title: "CinnamonBun"
theme: jekyll-theme-dinky

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

github_icon: "images/github-icon.png"
show_downloads: true

plugins:
  - jemoji
